from pydantic import BaseModel, Field


class WorkflowTask(BaseModel):
    """
    One task generated by the LLM.
    """

    id: int

    name: str

    service: str

    action: str

    description: str

    payload: dict = Field(default_factory=dict)

    depends_on: list[int] = Field(default_factory=list)


class WorkflowPlan(BaseModel):
    """
    Entire execution plan produced by the planner.
    """

    tasks: list[WorkflowTask] = Field(default_factory=list)