from pydantic import BaseModel, Field


class WorkflowTask(BaseModel):
    """
    One task generated by the LLM.
    """

    service: str
    action: str
    description: str
    depends_on: list[int] = Field(default_factory=list)


class WorkflowPlan(BaseModel):
    """
    Entire execution plan produced by the planner.
    """

    tasks: list[WorkflowTask] = Field(default_factory=list)