"""
Workflow Converter

Converts an AI-generated WorkflowPlan into the runtime Workflow model.
"""

from agentops.ai.planning.models import WorkflowPlan
from agentops.domains.workflows.workflow import Workflow
from agentops.domains.workflows.workflow_step import WorkflowStep


class WorkflowConverter:
    """
    Converts WorkflowPlan into Workflow.
    """

    def convert(
        self,
        plan: WorkflowPlan,
    ) -> Workflow:

        return Workflow(
            name="AI Workflow",
            description="Workflow generated by AI Planner",
            steps=[
                WorkflowStep(
                    id=task.id,
                    name=task.name,
                    service=task.service,
                    action=task.action,
                    description=task.description,
                    payload=task.payload,
                    depends_on=task.depends_on,
                )
                for task in plan.tasks
            ],
        )