"""
Chat API Schemas
"""

from pydantic import BaseModel, Field

from agentops.domains.research.analysis_models import CompanyAnalysis


class ChatRequest(BaseModel):
    """
    Chat request payload.
    """

    message: str = Field(
        ...,
        description="User message or prompt.",
        examples=[
            "Analyze MTN Nigeria",
            "Tell me about Flutterwave",
            "Research Dangote Cement",
        ],
    )


class ChatResponse(BaseModel):
    """
    Structured response returned by the AI assistant.
    """

    response: CompanyAnalysis = Field(
        ...,
        description="Structured company analysis generated by the AI assistant.",
    )