"""create opportunities table

Revision ID: f47b63a3a116
Revises: adfdb799198a
Create Date: 2026-07-20 15:40:24.412863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f47b63a3a116"
down_revision: str | Sequence[str] | None = "adfdb799198a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "organization_id",
            sa.String(length=100),
            server_default="demo-org",
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "researching",
                "proposal_drafted",
                "quotation_ready",
                "awaiting_approval",
                "sent",
                "negotiation",
                "won",
                "lost",
                name="opportunitystatus",
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="opportunitypriority"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "email",
                "website",
                "linkedin",
                "whatsapp",
                "telegram",
                "manual",
                "api",
                name="opportunitysource",
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunities_organization_id"),
        "opportunities",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.create_index(
        op.f("ix_opportunities_status"),
        "opportunities",
        ["status"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_opportunities_status"),
        table_name="opportunities",
    )
    op.drop_table("opportunities")
    # ### end Alembic commands ###
