"""
Analysis Data Model.

Holds all analysis generated by Analysis Agents.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class AnalysisData(BaseModel):
    """
    Structured analytical outputs.
    """

    business: dict = Field(default_factory=dict)

    financial: dict = Field(default_factory=dict)

    executive_summary: str | None = None
